In [5]:
import os
import collections
import numpy as np
import pandas as pd
from mnist import MNIST
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [6]:
mnistImagens = MNIST('imagens')
        
# Método para processamento de teste aprendizado
def processoTeste():
    imagens, labels = mnistImagens.load_training()
    
    # Método de fábrica para criar subclasses de tupla com campos nomeados
    teste = collections.namedtuple('teste', ['imagens', 'labels'])
    
    return teste(imagens, labels)
    
# Método para processamento de treino aprendizado
def processoTreino():
    imagens, labels = mnistImagens.load_testing()
    
    # Método de fábrica para criar subclasses de tupla com campos nomeados
    treino = collections.namedtuple('treino', ['imagens', 'labels'])
    return treino(imagens, labels)

# Algoritmo KNN

In [7]:
treino = processoTreino()
#treino

In [8]:
teste = processoTeste()

# Crie uma matriz
treinoImagem = np.array(treino.imagens)
treinoImagem

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [9]:
treinoLabels = np.array(treino.labels)
treinoImagem

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [10]:
print('Matriz da Soma das linhas do arquivo de treino: ' + str(treinoLabels))

Matriz da Soma das linhas do arquivo de treino: [7 2 1 ... 4 5 6]


In [11]:
# Crie uma matriz
testeImagem = np.array(teste.imagens)
testeImagem

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
testeLabels = np.array(teste.labels)    
testeLabels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [14]:
print('Matriz da Soma das linhas do arquivo de teste: ' + str(testeLabels))

Matriz da Soma das linhas do arquivo de teste: [5 0 4 ... 5 6 8]


In [15]:
n_neighbors = 3
print('Classificando Vizinhos k = ' + str(n_neighbors))

Classificando Vizinhos k = 3


In [16]:
# Encontra os Vizinhos mais proximos ao valor de K
classificadorVizinhos = KNeighborsClassifier(n_neighbors)

# Ajustar o modelo usando o paramêtro 1 como dados de treinamento e 
# paramêtro 2 como valores de destino
classificadorVizinhos.fit(treinoImagem, treinoLabels)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
# Prever os rótulos de classe para os dados fornecidos
precisao = classificadorVizinhos.predict(testeImagem)
precisao

In [ ]:
# Pontuação de classificação de precisão.
print('Precisão: ' + str(accuracy_score(testeLabels, precisao) * 100) + '%')

In [ ]:
print("Matriz de Confusão KNN")
# Compute a matriz de confusão para avaliar a precisão de uma classificação
pd.crosstab(testeLabels, precisao, rownames=['Real'], colnames=['Predito'], margins=True)

# Algoritmo LDA

In [11]:
treino = processoTreino() 

# Crie uma matriz
treinoImagem = np.array(treino.imagens)
treinoImagem

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
treinoLabels = np.array(treino.labels)
treinoLabels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [13]:
print('Soma das linhas do arquivo de treino: ' + str(treinoLabels))

Soma das linhas do arquivo de treino: [7 2 1 ... 4 5 6]


In [14]:
teste = processoTeste()

# Crie uma matriz
testeImagem = np.array(teste.imagens)
testeImagem

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
testeLabels = np.array(teste.labels)
testeLabels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [17]:
print('Soma das linhas do arquivo de teste: ' + str(testeLabels))

Soma das linhas do arquivo de teste: [5 0 4 ... 5 6 8]


In [18]:
# Um classificador com um limite de decisão linear, 
# gerado pela montagem de densidades condicionais de classe 
# aos dados e usando a regra de Bayes.
AnalisadorDiscriminante = LinearDiscriminantAnalysis()
        
# Ajuste o modelo LinearDiscriminantAnalysis de acordo com os dados e parâmetros de treinamento fornecidos.
AnalisadorDiscriminante.fit(treinoImagem, treinoLabels)

LinearDiscriminantAnalysis()

In [19]:
# Prever os rótulos de classe para os dados fornecidos
precisao = AnalisadorDiscriminante.predict(testeImagem)
precisao

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [20]:
print('Precisão: ' + str(accuracy_score(testeLabels, precisao) * 100) + '%')

Precisão: 85.08333333333333%


In [22]:
print("Matriz de Confusao LDA")
# Compute a matriz de confusão para avaliar a precisão de uma classificação        
pd.crosstab(testeLabels, precisao, rownames=['Real'], colnames=['Predito'], margins=True)

Matriz de Confusao LDA


Predito     0     1     2     3     4     5     6     7     8     9    All
Real                                                                      
0        5522     5    35    54    39   105    37     3   110    13   5923
1           0  6510    48    21    23    33     6    14    78     9   6742
2          78   198  4812   185   136    30   180    84   213    42   5958
3          23    99   236  4954    41   251    19   127   210   171   6131
4           9    50    43     7  5067    48    45     5    97   471   5842
5          64    77    39   310    93  4215   135    31   325   132   5421
6          64    81    88     8    76   137  5302     3   152     7   5918
7          40   137    42    64   210    30     5  5209    34   494   6265
8          29   417    52   225    84   309    30    20  4514   171   5851
9          47    27    15    90   350    35     1   362    77  4945   5949
All      5876  7601  5410  5918  6119  5193  5760  5858  5810  6455  60000